### ISSUE TITLE
Publishing to AUR

### ISSUE THREAD

**Issue by BachoSeven** [braph/nbfc-linux#1]
Hei, I currently maintain `nbfc` and `nbfc-git`, but since the official `nbfc` seems unmaintained, I was glad to find this project. Would you consider publishing this to the aur? I can do it as well, but it looks like you already have pkgbuilds for it so may as well..

Thanks for making this!

Edit: btw you should consider adding a `pkgver()` function to the `-git` package

**Comment by braph** [comment]
Hello! Sorry for replying late, I'm lacking a bit of motivation at the time ;)

I fixed the error you encountered by rewriting the Makefiles. Seems like the auto-generated files were missing in your build. I think providing only one PKGBUILD (depending on the github releases + checksum) is sufficient and also more safe.

**Comment by BachoSeven** [comment]
Hei again, I decided to publish the `-git` [version](https://aur.archlinux.org/packages/nbfc-linux-git) to the AUR as well(now builds correctly), since it's common for packages to be available this way in there. So, I'm going to go ahead and close this issue now.
