### ISSUE TITLE
Can't open PID file

### ISSUE THREAD

**Issue by BlueQuantumx** [braph/nbfc-linux#11]
nbfc failed to start on my Manjaro Unstable.
However, it's not completely failed, i edited the systemd service file, commented the line "Restart=on
-failure", only then i can see the  error log. Otherwise, nbfc will start finally, but it still made 6 red letters "Failed" on my startup screen, which upset me a lot.

Here are the logs:
7/15/21 7:37 AM	kernel	random: nbfc: uninitialized urandom read (24 bytes read)
7/15/21 7:37 AM	nbfc	Using 'Xiaomi Mi Book (TM1613, TM1703)' as model config
7/15/21 7:37 AM	nbfc	Using 'ECSysLinux' as EmbeddedControllerType
7/15/21 7:37 AM	nbfc	No sources found
7/15/21 7:37 AM	systemd	nbfc_service.service: Can't open PID file /var/run/nbfc_service.pid (yet?) after start: Operation not permitted
7/15/21 7:37 AM	systemd	nbfc_service.service: Failed with result 'protocol'.
7/15/21 7:37 AM	audit	SERVICE_START pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=nbfc_service comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=failed'

**Comment by braph** [comment]
Hello! The PID file is not written because the service cannot start up properly. It fails to find the temperature sources (`No sources found`) For fixing this I need the output of `cat /sys/class/hwmon/*/name`

**Comment by BlueQuantumx** [comment]
>> cat /sys/class/hwmon/*/name
ADP1
acpitz
BAT0
nvme
iwlwifi_1
coretemp

**Comment by braph** [comment]
The output of `cat` looks good, it lists `coretemp`. I cannot say why it fails. Maybe the output of `ls /sys/class/hwmon` can be helpful. Thanks

**Comment by BlueQuantumx** [comment]
ls /sys/class/hwmon                                                                                                                        ✔ 
hwmon0  hwmon1  hwmon2  hwmon3  hwmon4  hwmon5

**Comment by braph** [comment]
The files in `/sys/class/hwmon` look good so far, I still cannot see why it fails.
Can you send me the output of `sudo strace nbfc_service 2> OUTPUT_FILE`? Thanks

**Comment by BlueQuantumx** [comment]
Emmmmmm, I guess I have found something that truly matters.
I wrote a service to execute `ls /sys/class/hwmon`, and I found that when the service was on its first time to start, it only output from hwmon0 to hwmon3.
So I suspect it is because the nbfc started before the hwmon devices were all loaded.
So how to solve it?

**Comment by braph** [comment]
Thanks for that helpful report!
Does adding
```
[Unit]
After=basic.target
```
Solve the problem for you?

**Comment by BlueQuantumx** [comment]
No. Sitll failed.

**Comment by braph** [comment]
What about:
```
[Service]
ExecStartPre=/bin/sleep 30
```

**Comment by braph** [comment]
Sorry, this is a bad idea...

**Comment by braph** [comment]
I will solve this issue by adding a --delay option to the service

**Comment by braph** [comment]
Hello again, I fixed the issue by changing the systemd service file. It now waits for the `/sys/class/hwmon` files to be populated.
Can you give me feedback if it works for you? Thanks!

btw, you need to checkout the new version

**Comment by BlueQuantumx** [comment]
Well done! It works perfectly for me.
