### ISSUE TITLE
XML Config Support

### ISSUE THREAD

**Issue by CilekciGs** [braph/nbfc-linux#15]
Hello, I have an omen dc00xxxx and The config file I use in windows is xml. and since there is no support for xml in this version can you please add it to the package ?

https://github.com/hirschmann/nbfc/issues/749

**Comment by braph** [comment]
Done :)

**Comment by CilekciGs** [comment]
Thank you for your reply, It gives me an error

Using 'HP Omen 15-dc00xxxx' as model config
FanConfigurations[0]: TemperatureThresholds[4]: UpThreshold must be lower than critical temperature

**Comment by CilekciGs** [comment]
This Causes the error 

>
 	  {
	   "UpThreshold": 90,
	   "DownThreshold": 84,
	   "FanSpeed": 100.0
	  },
Bumping the critical temp up to 91 fixes it. 
and It performs about the same.
 this is a jank solution but it works

another (I'm Not sure about this one) solution is to lower the TemperatureThreshold to 88

**Comment by braph** [comment]
Thanks, I fixed it.
