### ISSUE TITLE
`-r/--recommend` is broken on 0.1.4

### ISSUE THREAD

**Issue by BachoSeven** [braph/nbfc-linux#16]
On the latest release, even though both the Makefile and README indicate that the configs now leave in `/usr/share/nbfc/configs`, running `sudo nbfc config -r` returns:
``` sh
Error: [Errno 2] No such file or directory: '/etc/nbfc/configs' 
```
as that is the path used by the python service(i.e. at https://github.com/braph/nbfc-linux/blob/6154a189119e5b56823c11b29b0210cba64dd1c3/nbfc.py#L39).

**Comment by braph** [comment]
Fixed, thanks for that observation!!!
