### ISSUE TITLE
Segmentation fault under linux-lqx on Asus ROG GL702ZC

### ISSUE THREAD

**Issue by jonathonf** [braph/nbfc-linux#5]
```
$ uname -a
Linux strix 5.12.7-lqx1-1-lqx #1 ZEN SMP PREEMPT Wed, 26 May 2021 14:40:20 +0000 x86_64 GNU/Linux
```
```
$ sudo nbfc config -a "Asus ROG GL702ZC"
$ sudo modprobe ec_sys
$ sudo nbfc start    
Using Asus ROG GL702ZC
$ sudo nbfc status -a
Error: Service not running
$ sudo nbfc_service -d
Using Asus ROG GL702ZC
[1]    15759 segmentation fault  sudo nbfc_service -d
```

Full strace: http://ix.io/3o6M

Edit: I wonder if it's down to expecting `ec_sys.write_support=1`... https://wiki.archlinux.org/title/Fan_speed_control#Configuration_2

**Comment by BachoSeven** [comment]
@jonathonf About your edit: even though using the original `nbfc` app I didn't need to do so on the same hardware, with this version I could not get it to work without `ec_sys.write_support=1` in my kernel cmdline.

host: Asus UX310UQK laptop, Arch Linux with 5.12.7-zen1-1-zen kernel.

**Comment by braph** [comment]
The nbfc_service automatically loads the `ec_sys` kernel module with write support enabled.
However, you can try out an alternative implementation for talking to the embedded controller using `--embedded-controller=ec_linux` (don't forget to stop the running service). If this worked, you can make the configuration permanent by setting it in `/etc/nbfc/nbfc.json` like this:
```{"TargetFanSpeeds": [0.0], "SelectedConfigId": "HP EliteBook 8560w", "EmbeddedControllerType": "ECLinux"}```

**Comment by braph** [comment]
I am closing this, as I have no solution for this problem.
