### ISSUE TITLE
I make this source code found a ERROR

### ISSUE THREAD

**Issue by 1433223anpeng** [braph/nbfc-linux#7]
(cd src; make nbfc_service)
make[1]: 进入目录“/home/anp/nbfc-linux/src”
cc  -DHAVE_SENSORS -Wall -Wextra -Os -DNDEBUG -s build.c -lsensors -lm -o nbfc_service
In file included from build.c:5:
lm_sensors.c:8:10: fatal error: sensors/error.h: 没有那个文件或目录
 #include <sensors/error.h>
          ^~~~~~~~~~~~~~~~~
compilation terminated.
make[1]: *** [Makefile:58：nbfc_service] 错误 1
make[1]: 离开目录“/home/anp/nbfc-linux/src”
make: *** [Makefile:54：src/nbfc_service] 错误 2

How to solve this problem？
HELP ME   
THANK YOU
My Notebook is ThundeRobot 911 me
i7 9750 gtx1650mq

**Comment by braph** [comment]
You are missing the `lm_sensors` package.

**Comment by 1433223anpeng** [comment]
but I install this package 
> dpkg -l lm-sensors
期望状态=未知(u)/安装(i)/删除(r)/清除(p)/保持(h)
| 状态=未安装(n)/已安装(i)/仅存配置(c)/仅解压缩(U)/配置失败(F)/不完全安装(H)/触发器等待(W)/触发器未决(T)
|/ 错误?=(无)/须重装(R) (状态，错误：大写=故障)
||/ 名称           版本         体系结构     描述
+++-==============-============-============-=================================================
ii  lm-sensors     1:3.5.0-3    amd64        utilities to read temperature/voltage/fan sensors

**Comment by braph** [comment]
Can you please give me a list of files contained in lm-sensors on your distribution? Maybe I should create a build script or use the Gnu autotools...

**Comment by 1433223anpeng** [comment]
> dpkg -L lm-sensors
/.
/etc
/etc/init.d
/etc/init.d/lm-sensors
/lib
/lib/systemd
/lib/systemd/system
/lib/systemd/system/lm-sensors.service
/usr
/usr/bin
/usr/bin/sensors
/usr/bin/sensors-conf-convert
/usr/sbin
/usr/sbin/isadump
/usr/sbin/isaset
/usr/sbin/sensors-detect
/usr/share
/usr/share/doc
/usr/share/doc/lm-sensors
/usr/share/doc/lm-sensors/README.Debian.gz
/usr/share/doc/lm-sensors/applications
/usr/share/doc/lm-sensors/changelog.Debian.gz
/usr/share/doc/lm-sensors/changelog.gz
/usr/share/doc/lm-sensors/copyright
/usr/share/doc/lm-sensors/donations.gz
/usr/share/doc/lm-sensors/examples
/usr/share/doc/lm-sensors/examples/daemon
/usr/share/doc/lm-sensors/examples/daemon/healthd.sh
/usr/share/doc/lm-sensors/examples/hotplug
/usr/share/doc/lm-sensors/examples/hotplug/README.p4b
/usr/share/doc/lm-sensors/examples/hotplug/unhide_ICH_SMBus
/usr/share/doc/lm-sensors/examples/tellerstats
/usr/share/doc/lm-sensors/examples/tellerstats/README
/usr/share/doc/lm-sensors/examples/tellerstats/gather.sh
/usr/share/doc/lm-sensors/examples/tellerstats/gnuplotscript.tmpl
/usr/share/doc/lm-sensors/examples/tellerstats/index.shtml
/usr/share/doc/lm-sensors/examples/tellerstats/tellerstats.conf
/usr/share/doc/lm-sensors/examples/tellerstats/tellerstats.sh
/usr/share/doc/lm-sensors/fan-divisors.gz
/usr/share/doc/lm-sensors/temperature-sensors
/usr/share/doc/lm-sensors/vid
/usr/share/man
/usr/share/man/man1
/usr/share/man/man1/sensors.1.gz
/usr/share/man/man5
/usr/share/man/man5/sensors.conf.5.gz
/usr/share/man/man8
/usr/share/man/man8/isadump.8.gz
/usr/share/man/man8/isaset.8.gz
/usr/share/man/man8/sensors-conf-convert.8.gz
/usr/share/man/man8/sensors-detect.8.gz
[10:34:36] anp@anp-PC /home/anp (0) 
> 

Is that it？
thank you

**Comment by braph** [comment]
Try it again with `libsensors` package installed

**Comment by 1433223anpeng** [comment]
> sudo apt install libsensors
请输入密码:
验证成功
正在读取软件包列表... 完成
正在分析软件包的依赖关系树       
正在读取状态信息... 完成       
E: 无法定位软件包 libsensors


Unable to locate package

not  have this package

**Comment by braph** [comment]
Sorry, the package name is `libsensors-dev`

**Comment by braph** [comment]
Then install that package ;)

**Comment by 1433223anpeng** [comment]
no I source not have this package

请输入密码:
验证成功
正在读取软件包列表... 完成
正在分析软件包的依赖关系树       
正在读取状态信息... 完成       
注意，选中 'libsensors4-dev' 而非 'libsensors-dev'
libsensors4-dev 已经是最新版 (1:3.5.0-3)。
升级了 0 个软件包，新安装了 0 个软件包，要卸载 0 个软件包，有 0 个软件包未被升级。

**Comment by braph** [comment]
Okay, it seems that you already have installed `libsensors-dev`, and the package should contain the files
```
/usr/include/sensors/error.h
/usr/include/sensors/sensors.h
```
I don't see any reason why the build fails for you.
However, I dropped the dependency for `libsensors-dev`. If you checkout the new version of the repository it should work now.

**Comment by 1433223anpeng** [comment]
thank you 
but now My notebook not in set config list ,I don't know how do it
My notebook is intel i7 9750H gtx1650mq.
thank you

**Comment by braph** [comment]
I am not able to help you with this issue. I would need to have this notebook model myself for trying to write a config file for it. Even then it would not be a trivial task. I am sorry for you.

**Comment by BachoSeven** [comment]
@1433223anpeng if you would like to write a config file for it yourself, you might want to have a look at the original `nbfc` project's [wiki](https://github.com/hirschmann/nbfc/wiki/How-to-create-a-NBFC-config).

**Comment by 1433223anpeng** [comment]
I create a config file .Now i can control my notebook fans.
thaks
