### ISSUE TITLE
"/usr/bin/ld: cannot find -lsensors "  Error While make Command

### ISSUE THREAD

**Issue by Srikeshram** [braph/nbfc-linux#8]
I have cloned the repository, and while trying to install the nbfc-linux using the command `make && sudo make install
`, it shows the following error `/usr/bin/ld: cannot find -lsensors` and exits the make process. I am using the Ubuntu 20.04. Kindly help me to solve the issue.

**Comment by braph** [comment]
Clone the repository and try it out again. I dropped `-lsensors` from the Makefile.

**Comment by Srikeshram** [comment]
@braph Thanks for the solution. Does removing -lsensors in makefile will cause any issue?

**Comment by braph** [comment]
No, nbfc-linux does provide two implementations to read the CPU temperature, one depending on `lm_sensors` and one without.
Until I found out why `lm_sensors` causes problems on some distributions I will leave it out.
